<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:21 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:Text>[TOTGROMASHEA307] is '123456789.012'</err:Text>
  </err:Error>
</err:ErrorResponse>
