<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:23 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8625</err:Number>
    <err:Type>business</err:Type>
    <err:Text>If the data group 'Trader Consignee' is used then the data group 'Goods Item Trader Consignee' can not be used (C584)</err:Text>
    <err:Location>/ie:CC313A[1]/GOOITEGDS[1]/TRACONCE2[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8632</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Street and Number (box 8) within Import Operation.Trader Consignee must not be present if the GB 'TIN' has been declared (C501)</err:Text>
    <err:Location>/ie:CC313A[1]/TRACONCE1[1]/StrAndNumCE122[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
