<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:24 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8135</err:Number>
    <err:Type>business</err:Type>
    <err:Text>If the field IMPORT OPERATION Transport charges – 'Method of payment' is used then the field GOODS ITEM Transport Charges – 'Method of payment' cannot be used (C576)</err:Text>
    <err:Location>/ie:CC313A[1]/GOOITEGDS[1]/MetOfPayGDI12[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
