<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:22 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8626</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Name (box 2)' within  Import Operation.Trader Consignor must not be present if the GB 'TIN' has been declared (C501)</err:Text>
    <err:Location>/ie:CC313A[1]/TRACONCO1[1]/NamCO17[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
