<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:23 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8619</err:Number>
    <err:Type>business</err:Type>
    <err:Text>If 'Special Mention Additional Information_id' does not equal '10600' for at least one 'Goods item' then the data group 'Trader notify party' can not be used (C583)</err:Text>
    <err:Location>/ie:CC313A[1]/NOTPAR670[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8640</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Country Code' within Import Operation.Notify Party must not be present if the GB 'TIN' has been declared (C501)</err:Text>
    <err:Location>/ie:CC313A[1]/NOTPAR670[1]/CouCodNOTPAR675[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
