<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:26 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8160</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Street and Number' within Trader at Entry (Carrier) is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC313A[1]/TRACARENT601[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8161</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Postcode' within Trader at Entry (Carrier) is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC313A[1]/TRACARENT601[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8162</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'City' within Trader at Entry (Carrier) is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC313A[1]/TRACARENT601[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8163</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Country Code' within Trader at Entry (Carrier) is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC313A[1]/TRACARENT601[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
