<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:21 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8677</err:Number>
    <err:Type>business</err:Type>
    <err:Text>Value must have at least one digit before and after the decimal point if the decimal point is present</err:Text>
    <err:Location>/ie:CC313A[1]/HEAHEA[1]/TotGroMasHEA307[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
