<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:26 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8149</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The fields 'Number of Packages (box 31)' and 'Number of Pieces (box31)' cannot be used if 'Kind of Packages (box31)' indicates 'BULK' (UNECE rec 21 : 'VQ', 'VG', 'VL', 'VY', 'VR', 'VS' or 'VO') (C062)</err:Text>
    <err:Location>/ie:CC313A[1]/GOOITEGDS[1]/PACGS2[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8117</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The 'Total Number of Packages' is equal to the sum of all 'Number of Packages' + all 'Number of pieces' + a value of '1' for each declared 'bulk' (R105)</err:Text>
    <err:Location>/ie:CC313A[1]/HEAHEA[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
