<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:23 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8687</err:Number>
    <err:Type>business</err:Type>
    <err:Text>If the field 'Specific Circumstance Indicator' does not = 'E' and Import Operation 'Unloading Place' is not used then Goods Item 'Unloading Place' is required (C579)</err:Text>
    <err:Location>/ie:CC313A[1]/GOOITEGDS[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8691</err:Number>
    <err:Type>business</err:Type>
    <err:Text>[Specific circumstance indicator] may only take the values ‘C’, ‘D’ or ‘E’</err:Text>
    <err:Location>/ie:CC313A[1]/HEAHEA[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
