<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:26 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8622</err:Number>
    <err:Type>business</err:Type>
    <err:Text>If 'Special Mention Additional Information_id' = '10600' is used in this GOODS ITEM and the data group 'Trader Notify party' is not used THEN the data group 'GOODS ITEM TRADER Notify party' is Required (C584)</err:Text>
    <err:Location>/ie:CC313A[1]/GOOITEGDS[3]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8622</err:Number>
    <err:Type>business</err:Type>
    <err:Text>If 'Special Mention Additional Information_id' = '10600' is used in this GOODS ITEM and the data group 'Trader Notify party' is not used THEN the data group 'GOODS ITEM TRADER Notify party' is Required (C584)</err:Text>
    <err:Location>/ie:CC313A[1]/GOOITEGDS[2]</err:Location>
  </err:Error>
</err:ErrorResponse>
