<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:22 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8103</err:Number>
    <err:Type>business</err:Type>
    <err:Text>Gross Mass' should be present if 'Specific Circumstance indicator' does not equal 'E' OR there is no 'Total Gross Mass' (C592)</err:Text>
    <err:Location>/ie:CC313A[1]/GOOITEGDS[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8103</err:Number>
    <err:Type>business</err:Type>
    <err:Text>Gross Mass' should be present if 'Specific Circumstance indicator' does not equal 'E' OR there is no 'Total Gross Mass' (C592)</err:Text>
    <err:Location>/ie:CC313A[1]/GOOITEGDS[2]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8103</err:Number>
    <err:Type>business</err:Type>
    <err:Text>Gross Mass' should be present if 'Specific Circumstance indicator' does not equal 'E' OR there is no 'Total Gross Mass' (C592)</err:Text>
    <err:Location>/ie:CC313A[1]/GOOITEGDS[3]</err:Location>
  </err:Error>
</err:ErrorResponse>
