<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:29 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8122</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Postcode (box 2)' within Import Operation.Trader Consignor is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/TRACONCO1[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8120</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Name (box 2)' wiithin  Import Operation.Trader Consignor is required if no 'TIN' has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/TRACONCO1[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8121</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Street and Number (box 2)' within Import Operation.Trader Consignor is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/TRACONCO1[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8123</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'City (box 2)' within Import Operation.Trader Consignor is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/TRACONCO1[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8124</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Country (box 2)' within Import Operation.Trader Consignor is required if no 'TIN' has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/TRACONCO1[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
