<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:31 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8137</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Name (box 2)' within Goods Item.Trader Consignor is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[1]/TRACONCO2[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8137</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Name (box 2)' within Goods Item.Trader Consignor is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[2]/TRACONCO2[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8138</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Street and Number (box 2)' within Goods Item.Trader consignor  is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[1]/TRACONCO2[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8138</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Street and Number (box 2)' within Goods Item.Trader consignor  is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[2]/TRACONCO2[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8139</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The 'Postcode (box 2)' within Goods Item.Trader Consignor is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[1]/TRACONCO2[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8139</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The 'Postcode (box 2)' within Goods Item.Trader Consignor is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[2]/TRACONCO2[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8140</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'City (box 2)' within Goods Item.Trader Consignor is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[2]/TRACONCO2[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8141</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Country (box 2)' within Goods Item.Trader Consignor is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[1]/TRACONCO2[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8141</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Country (box 2)' within Goods Item.Trader Consignor is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[2]/TRACONCO2[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
