<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:28 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8685</err:Number>
    <err:Type>business</err:Type>
    <err:Text>IF [Transport mode at border] = '1' AND [Conveyance reference number] begins with "XFER" THEN [Conveyance reference number] must consist of the letters "XFER" followed by one or more alphanumeric characters, which can optionally be followed by a separator (":" (colon) or "-" (hyphen)) and one or more alphanumeric characters (TR0519)</err:Text>
    <err:Location>/ie:CC315A[1]/HEAHEA[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
