<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:32 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8154</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Name' within Goods Item.Notify Party is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[1]/PRTNOT640[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8155</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Street and Number' within Goods Item.Notify Party is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[1]/PRTNOT640[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8156</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Postcode' within Goods Item.Notify Party is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[1]/PRTNOT640[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8158</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Country Code' within Goods Item.Notify Party is required if no TIN has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[1]/PRTNOT640[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
