<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:27 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8644</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'City (box 2)' within Goods Item.Trader Consignor must not be present if the GB 'TIN' has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[1]/TRACONCO2[1]/CitCO224[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8641</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Name (box 2)' within Goods Item.Trader Consignor must not be present if the GB 'TIN' has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[1]/TRACONCO2[1]/NamCO27[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8643</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Postcode (box 2)' within Goods Item.Trader Consignor must not be present if the GB 'TIN' has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[1]/TRACONCO2[1]/PosCodCO223[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8642</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Street and Number (box 2)' within Goods Item.Trader Consignor must not be present if the GB 'TIN' has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[1]/TRACONCO2[1]/StrAndNumCO222[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8644</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'City (box 2)' within Goods Item.Trader Consignor must not be present if the GB 'TIN' has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[2]/TRACONCO2[1]/CitCO224[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8645</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Country (box 2)' within Goods Item.Trader Consignor must not be present if the GB 'TIN' has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[2]/TRACONCO2[1]/CouCO225[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8641</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Name (box 2)' within Goods Item.Trader Consignor must not be present if the GB 'TIN' has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[2]/TRACONCO2[1]/NamCO27[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8643</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Postcode (box 2)' within Goods Item.Trader Consignor must not be present if the GB 'TIN' has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[2]/TRACONCO2[1]/PosCodCO223[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8642</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Street and Number (box 2)' within Goods Item.Trader Consignor must not be present if the GB 'TIN' has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[2]/TRACONCO2[1]/StrAndNumCO222[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8117</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The 'Total Number of Packages' is equal to the sum of all 'Number of Packages' + all 'Number of pieces' + a value of '1' for each declared 'bulk' (R105)</err:Text>
    <err:Location>/ie:CC315A[1]/HEAHEA[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
