<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:27 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8684</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Itinerary' must occur at least twice (min. 2 values) (C570)</err:Text>
    <err:Location>/ie:CC315A[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
