<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:33 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8656</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The 'Name' field of (Representative) Trader must not be present if the 'TIN' has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/TRAREP[1]/NamTRE1[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
