<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:29 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8204</err:Number>
    <err:Type>business</err:Type>
    <err:Text>If 'Special Mention Additional Information_id' = '10600' and is used for at least one 'Goods Item' then data group 'Trader Consignee' can not be used (C583)</err:Text>
    <err:Location>/ie:CC315A[1]/TRACONCE1[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
