<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:32 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8680</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The 'Number of Packages' field within 'Packages' must not contain leading zeros.</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[1]/PACGS2[1]/NumOfPacGS24[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
