<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:33 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8662</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The 'Street and Number' field of Person Lodging the Summary Declaration must not be present if the 'TIN' has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/PERLODSUMDEC[1]/StrAndNumPLD1[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
