<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:31 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8646</err:Number>
    <err:Type>business</err:Type>
    <err:Text>The field 'Name (box 8)' within Goods Item.Trader Consignee must not be present if the GB 'TIN' has been declared (C501)</err:Text>
    <err:Location>/ie:CC315A[1]/GOOITEGDS[1]/TRACONCE2[1]/NamCE27[1]</err:Location>
  </err:Error>
  <err:Error>
    <err:RaisedBy>ChRIS</err:RaisedBy>
    <err:Number>8691</err:Number>
    <err:Type>business</err:Type>
    <err:Text>[Specific circumstance indicator] may only take the values ‘C’, ‘D’ or ‘E’</err:Text>
    <err:Location>/ie:CC315A[1]/HEAHEA[1]</err:Location>
  </err:Error>
</err:ErrorResponse>
