<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:27 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:Text>Two instances of [TRACONCO2] present; differ only in that [POSCODCO223] is absent in the first and empty in the second.</err:Text>
  </err:Error>
</err:ErrorResponse>
