<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:32 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:Text>Three instances of [PACGS2] within different [GOOITEGDS]s: The first [MARNUMOFPACGSL21] is ''; the second [MARNUMOFPACGSL21] is absent; they are not considered to match, so the first [NUMOFPACGS24] being zero causes an error.</err:Text>
  </err:Error>
</err:ErrorResponse>
