<?xml version="1.0" encoding="UTF-8"?>
<!--
  Test case control file
  Generated by CoreFiling: Fri Jan 11 11:11:31 GMT 2019
-->
<err:ErrorResponse xmlns:err="http://www.govtalk.gov.uk/CM/errorresponse" xmlns:dsl="http://decisionsoft.com/rim/errorExtension" SchemaVersion="2.0">
  <err:Error>
    <err:Text>[SPECIRINDHEA1] is 'e' (lower-case, not equal to 'E'), [TRACONCE2] is present, but [TINCE259] is absent</err:Text>
  </err:Error>
</err:ErrorResponse>
